/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    loads: Load;
    customers: Customer;
    'customer-locations': CustomerLocation;
    carriers: Carrier;
    media: Media;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    loads: LoadsSelect<false> | LoadsSelect<true>;
    customers: CustomersSelect<false> | CustomersSelect<true>;
    'customer-locations': CustomerLocationsSelect<false> | CustomerLocationsSelect<true>;
    carriers: CarriersSelect<false> | CarriersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  globals: {};
  globalsSelect: {};
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  name?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "loads".
 */
export interface Load {
  id: string;
  /**
   * Auto-generated or manual
   */
  loadNumber: string;
  status: 'booked' | 'dispatched' | 'in-transit' | 'delivered' | 'invoiced' | 'paid' | 'cancelled' | 'tonu';
  customer: string | Customer;
  customerRate: number;
  customerCurrency?: 'USD' | null;
  customerReferenceNumbers?: {
    poNumber?: string | null;
    bolNumber?: string | null;
    proNumber?: string | null;
  };
  pickupLocation?: (string | null) | CustomerLocation;
  pickupAddress?: {
    facilityName?: string | null;
    addressLine1?: string | null;
    city?: string | null;
    state?: string | null;
    zipCode?: string | null;
    contactName?: string | null;
    contactPhone?: string | null;
  };
  pickupDate: string;
  pickupDateEnd?: string | null;
  pickupAppointment?: boolean | null;
  pickupInstructions?: string | null;
  deliveryLocation?: (string | null) | CustomerLocation;
  deliveryAddress?: {
    facilityName?: string | null;
    addressLine1?: string | null;
    city?: string | null;
    state?: string | null;
    zipCode?: string | null;
    contactName?: string | null;
    contactPhone?: string | null;
  };
  deliveryDate: string;
  deliveryDateEnd?: string | null;
  deliveryAppointment?: boolean | null;
  deliveryInstructions?: string | null;
  equipmentType: 'dry-van' | 'reefer' | 'flatbed' | 'step-deck' | 'power-only' | 'hotshot' | 'box-truck';
  weight?: number | null;
  length?: number | null;
  palletCount?: number | null;
  commodity?: string | null;
  specialRequirements?: ('team' | 'hazmat' | 'temp-controlled' | 'liftgate' | 'inside-delivery' | 'tarps')[] | null;
  /**
   * e.g., "38-42°F"
   */
  temperature?: string | null;
  carrier?: (string | null) | Carrier;
  carrierRate?: number | null;
  /**
   * Auto-calculated
   */
  margin?: number | null;
  driverInfo?: {
    driverName?: string | null;
    driverPhone?: string | null;
    truckNumber?: string | null;
    trailerNumber?: string | null;
  };
  rateConSent?: boolean | null;
  rateConSentDate?: string | null;
  accessorials?:
    | {
        type: 'detention' | 'layover' | 'tonu' | 'lumper' | 'stop' | 'fuel' | 'other';
        description?: string | null;
        amount: number;
        billTo: 'customer' | 'carrier' | 'internal';
        id?: string | null;
      }[]
    | null;
  documents?: (string | Media)[] | null;
  requiredDocuments?: {
    hasBOL?: boolean | null;
    hasPOD?: boolean | null;
    hasRateCon?: boolean | null;
  };
  macropointTracking?: {
    trackingId?: string | null;
    trackingActive?: boolean | null;
    lastLocation?: string | null;
    lastUpdate?: string | null;
  };
  statusHistory?:
    | {
        status?: string | null;
        timestamp?: string | null;
        note?: string | null;
        id?: string | null;
      }[]
    | null;
  internalNotes?: string | null;
  dispatchNotes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "customers".
 */
export interface Customer {
  id: string;
  companyName: string;
  status: 'active' | 'inactive' | 'on-hold';
  primaryContact?: string | null;
  email?: string | null;
  phone?: string | null;
  alternatePhone?: string | null;
  additionalContacts?:
    | {
        name: string;
        email?: string | null;
        phone?: string | null;
        role?: string | null;
        id?: string | null;
      }[]
    | null;
  billingEmail?: string | null;
  paymentTerms?: ('due-on-receipt' | 'net-15' | 'net-30' | 'net-45' | 'net-60') | null;
  /**
   * Maximum outstanding balance allowed
   */
  creditLimit?: number | null;
  /**
   * Synced from QuickBooks
   */
  quickbooksCustomerId?: string | null;
  notes?: string | null;
  /**
   * Default instructions for loads from this customer
   */
  specialInstructions?: string | null;
  requiresPOD?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "customer-locations".
 */
export interface CustomerLocation {
  id: string;
  customer: string | Customer;
  /**
   * e.g., "Main Warehouse" or "Distribution Center"
   */
  locationName: string;
  locationType: 'pickup' | 'delivery' | 'both';
  addressLine1: string;
  addressLine2?: string | null;
  city: string;
  state: string;
  zipCode: string;
  contactName?: string | null;
  contactPhone?: string | null;
  /**
   * e.g., "Mon-Fri 8am-5pm"
   */
  hours?: string | null;
  appointmentRequired?: boolean | null;
  /**
   * Gate codes, parking instructions, etc.
   */
  specialInstructions?: string | null;
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "carriers".
 */
export interface Carrier {
  id: string;
  companyName: string;
  status: 'active' | 'inactive' | 'pending' | 'do-not-use';
  mcNumber: string;
  dotNumber: string;
  safetyRating?: ('satisfactory' | 'conditional' | 'unsatisfactory' | 'not-rated') | null;
  insuranceExpiration?: string | null;
  w9OnFile?: boolean | null;
  carrierPacketComplete?: boolean | null;
  approvedDate?: string | null;
  primaryContact?: string | null;
  email?: string | null;
  phone?: string | null;
  /**
   * Email for sending rate confirmations
   */
  dispatchEmail?: string | null;
  additionalContacts?:
    | {
        name: string;
        email?: string | null;
        phone?: string | null;
        role?: string | null;
        id?: string | null;
      }[]
    | null;
  equipmentTypes?: ('dry-van' | 'reefer' | 'flatbed' | 'step-deck' | 'power-only' | 'hotshot' | 'box-truck')[] | null;
  /**
   * e.g., "CA to TX", "Midwest regional"
   */
  preferredLanes?: string | null;
  serviceAreas?: string | null;
  paymentMethod?: ('standard' | 'quick-pay' | 'factoring') | null;
  factoringCompany?: string | null;
  /**
   * Synced from ePay
   */
  ePayCarrierId?: string | null;
  /**
   * Auto-calculated based on on-time %, claims, etc.
   */
  performanceScore?: number | null;
  onTimePercentage?: number | null;
  notes?: string | null;
  specialInstructions?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt?: string | null;
  documentType?:
    | (
        | 'bol'
        | 'pod'
        | 'rate-con'
        | 'invoice'
        | 'lumper'
        | 'detention'
        | 'insurance'
        | 'w9'
        | 'carrier-packet'
        | 'other'
      )
    | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'loads';
        value: string | Load;
      } | null)
    | ({
        relationTo: 'customers';
        value: string | Customer;
      } | null)
    | ({
        relationTo: 'customer-locations';
        value: string | CustomerLocation;
      } | null)
    | ({
        relationTo: 'carriers';
        value: string | Carrier;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "loads_select".
 */
export interface LoadsSelect<T extends boolean = true> {
  loadNumber?: T;
  status?: T;
  customer?: T;
  customerRate?: T;
  customerCurrency?: T;
  customerReferenceNumbers?:
    | T
    | {
        poNumber?: T;
        bolNumber?: T;
        proNumber?: T;
      };
  pickupLocation?: T;
  pickupAddress?:
    | T
    | {
        facilityName?: T;
        addressLine1?: T;
        city?: T;
        state?: T;
        zipCode?: T;
        contactName?: T;
        contactPhone?: T;
      };
  pickupDate?: T;
  pickupDateEnd?: T;
  pickupAppointment?: T;
  pickupInstructions?: T;
  deliveryLocation?: T;
  deliveryAddress?:
    | T
    | {
        facilityName?: T;
        addressLine1?: T;
        city?: T;
        state?: T;
        zipCode?: T;
        contactName?: T;
        contactPhone?: T;
      };
  deliveryDate?: T;
  deliveryDateEnd?: T;
  deliveryAppointment?: T;
  deliveryInstructions?: T;
  equipmentType?: T;
  weight?: T;
  length?: T;
  palletCount?: T;
  commodity?: T;
  specialRequirements?: T;
  temperature?: T;
  carrier?: T;
  carrierRate?: T;
  margin?: T;
  driverInfo?:
    | T
    | {
        driverName?: T;
        driverPhone?: T;
        truckNumber?: T;
        trailerNumber?: T;
      };
  rateConSent?: T;
  rateConSentDate?: T;
  accessorials?:
    | T
    | {
        type?: T;
        description?: T;
        amount?: T;
        billTo?: T;
        id?: T;
      };
  documents?: T;
  requiredDocuments?:
    | T
    | {
        hasBOL?: T;
        hasPOD?: T;
        hasRateCon?: T;
      };
  macropointTracking?:
    | T
    | {
        trackingId?: T;
        trackingActive?: T;
        lastLocation?: T;
        lastUpdate?: T;
      };
  statusHistory?:
    | T
    | {
        status?: T;
        timestamp?: T;
        note?: T;
        id?: T;
      };
  internalNotes?: T;
  dispatchNotes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "customers_select".
 */
export interface CustomersSelect<T extends boolean = true> {
  companyName?: T;
  status?: T;
  primaryContact?: T;
  email?: T;
  phone?: T;
  alternatePhone?: T;
  additionalContacts?:
    | T
    | {
        name?: T;
        email?: T;
        phone?: T;
        role?: T;
        id?: T;
      };
  billingEmail?: T;
  paymentTerms?: T;
  creditLimit?: T;
  quickbooksCustomerId?: T;
  notes?: T;
  specialInstructions?: T;
  requiresPOD?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "customer-locations_select".
 */
export interface CustomerLocationsSelect<T extends boolean = true> {
  customer?: T;
  locationName?: T;
  locationType?: T;
  addressLine1?: T;
  addressLine2?: T;
  city?: T;
  state?: T;
  zipCode?: T;
  contactName?: T;
  contactPhone?: T;
  hours?: T;
  appointmentRequired?: T;
  specialInstructions?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "carriers_select".
 */
export interface CarriersSelect<T extends boolean = true> {
  companyName?: T;
  status?: T;
  mcNumber?: T;
  dotNumber?: T;
  safetyRating?: T;
  insuranceExpiration?: T;
  w9OnFile?: T;
  carrierPacketComplete?: T;
  approvedDate?: T;
  primaryContact?: T;
  email?: T;
  phone?: T;
  dispatchEmail?: T;
  additionalContacts?:
    | T
    | {
        name?: T;
        email?: T;
        phone?: T;
        role?: T;
        id?: T;
      };
  equipmentTypes?: T;
  preferredLanes?: T;
  serviceAreas?: T;
  paymentMethod?: T;
  factoringCompany?: T;
  ePayCarrierId?: T;
  performanceScore?: T;
  onTimePercentage?: T;
  notes?: T;
  specialInstructions?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  documentType?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}